In [ ]:
import numpy as np #import numpy
x = np.array([[29, 6], [9, 61], [3, 8]]) #inisialisasi matrix berukuran 2x3
print(x) #tampilkan matrix
print(x.size) #tampilkan ukuran dari matrix X
print(x[:,0]) #tampilkan seluruh kolom pertama
print(x[1,:]) #tampilkan seluruh baris kedua

import torch
import tensorflow as tf
x = torch.tensor([[29, 6], [9, 61], [3, 8]]) #inisialisasi matrix berukuran 2x3 menggunaakan torch
print(x) #tampilkan matrix
print(x.shape) #tampilkan ukuran dari matrix X
print(x[:,0]) #tampilkan seluruh kolom pertama
print(x[1,:]) #tampilkan seluruh baris kedua
x = tf.Variable([[29, 6], [9, 61], [3, 8]]) #inisialisasi matrix berukuran 2x3 menggunaakan tensorflow
print(x) #tampilkan matrix
print(x.shape) #tampilkan ukuran dari matrix X
print(x[:,0]) #tampilkan seluruh kolom pertama
print(x[1,:]) #tampilkan seluruh baris kedua

[[29  6]
 [ 9 61]
 [ 3  8]]
6
[29  9  3]
[ 9 61]
tensor([[29,  6],
        [ 9, 61],
        [ 3,  8]])
torch.Size([3, 2])
tensor([29,  9,  3])
tensor([ 9, 61])
<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[29,  6],
       [ 9, 61],
       [ 3,  8]], dtype=int32)>
(3, 2)
tf.Tensor([29  9  3], shape=(3,), dtype=int32)
tf.Tensor([ 9 61], shape=(2,), dtype=int32)
