In [ ]:
import numpy as np #import numpy
x = np.array([9, 29, 61]) #inialisasi vektor
print(len(x)) #tampilkan panjang vektor
print(x.shape) #tampilkan bentuk vektor
print(type(x)) #tampilkan tipe data vektor
print(type(x[0])) #tampilkan tipe data dari elemen pertama

x_t = x.T # tranpose x dan massukan dalam x_t
print(x_t) #tampilkan tranpose x
print(x_t.shape) #tampilkan bentuk tranpose x
y = np.array([61, 29, 9]) #inisialisasi variabel y
y_t = y.T #tranpose x dan masukkan ke y_t
print(y_t) #tampilkan tranpose y
print(len(y_t)) #tampilakan ukuran dari y_t

import torch #import torch dari library
import tensorflow as tf #torch dari library
x_pt = torch.tensor([9, 29, 61]) #inisialisasi vektor menggunakan torch
print(x_pt) # tampilkan x_pt
x_pt_t = x_pt.T #tranpose x_pt dan masukkan ke x_pt_t
print(x_pt_t) #tampilkan x_pt_t
print(len(x_pt_t)) #tampilkan ukuran x_pt_t
y_pt = torch.tensor([61, 9, 29]) #inisialisasi vektor menggunakan torch
print(y_pt) # tampilkan y_pt
print(len(y_pt)) #tampilkan ukuran y_pt

x_pt = tf.Variable([9, 29, 61]) #inisialisasi vektor menggunakan tf
print(x_pt) # tampilkan x_pt
x_pt_t = tf.transpose(x_pt) #tranpose x_pt dan masukkan ke x_pt_t
print(x_pt_t) #tampilkan x_pt_t
print(len(x_pt_t)) #tampilkan ukuran x_pt_t
y_pt = tf.Variable([61, 9, 29]) #inisialisasi vektor menggunakan tf
print(y_pt) # tampilkan y_pt
print(y_pt.dtype) #tampilkan ukuran y_pt

3
(3,)
<class 'numpy.ndarray'>
<class 'numpy.int64'>
[ 9 29 61]
(3,)
[61 29  9]
3
tensor([ 9, 29, 61])
tensor([ 9, 29, 61])
3
tensor([61,  9, 29])
3
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([ 9, 29, 61], dtype=int32)>
tf.Tensor([ 9 29 61], shape=(3,), dtype=int32)
3
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([61,  9, 29], dtype=int32)>
<dtype: 'int32'>


/tmp/ipykernel_1711/2375506543.py:20: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /pytorch/aten/src/ATen/native/TensorShape.cpp:4480.)
  x_pt_t = x_pt.T #tranpose x_pt dan masukkan ke x_pt_t
