Soal 1

In [ ]:
import numpy as np
import torch
import tensorflow as tf

In [ ]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[25, 15, 6], [10, 47, 4]])
X

array([[25, 15,  6],
       [10, 47,  4]])

In [ ]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[25, 15, 6], [10, 47, 4]])
X_pt

tensor([[25, 15,  6],
        [10, 47,  4]])

In [ ]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[25, 15, 6], [10, 47, 4]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25, 15,  6],
       [10, 47,  4]], dtype=int32)>

In [ ]:
# lakukan perkalian matrix X dengan suatu skalar
X*2

array([[50, 30, 12],
       [20, 94,  8]])

In [ ]:
# lakukan perkalian matrix X_pt dengan suatu skalar
X_pt*2

tensor([[50, 30, 12],
        [20, 94,  8]])

In [ ]:
# lakukan perkalian matrix X_tf dengan suatu skalar
X_tf*2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[50, 30, 12],
       [20, 94,  8]], dtype=int32)>

In [ ]:
# lakukan penjumlahan matrix X dengan suatu skalar
X+2

array([[27, 17,  8],
       [12, 49,  6]])

In [ ]:
# lakukan penjumlahan matrix X_pt dengan suatu skalar
X_pt+2

tensor([[27, 17,  8],
        [12, 49,  6]])

In [ ]:
# lakukan penjumlahan matrix X_tf dengan suatu skalar
X_tf+2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[27, 17,  8],
       [12, 49,  6]], dtype=int32)>

In [ ]:
# lakukan pengurangan matrix X dengan suatu skalar
X-2

array([[23, 13,  4],
       [ 8, 45,  2]])

In [ ]:
# lakukan pengurangan matrix X_pt dengan suatu skalar
X_pt-2

tensor([[23, 13,  4],
        [ 8, 45,  2]])

In [ ]:
# lakukan pengurangan matrix X_tf dengan suatu skalar
X_tf-2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[23, 13,  4],
       [ 8, 45,  2]], dtype=int32)>

Soal 2

In [ ]:
# buat matrix Y dengan ukuran 2x3 menggunakan numpy
Y = np.array([[1, 2, 2], [4, 4, 1]])
Y

array([[1, 2, 2],
       [4, 4, 1]])

In [ ]:
# buat matrix Y_pt dengan ukuran 2x3 menggunakan pytorch
Y_pt = torch.tensor([[1, 2, 2], [4, 4, 1]])
Y_pt

tensor([[1, 2, 2],
        [4, 4, 1]])

In [ ]:
# buat matrix Y_tf dengan ukuran 2x3 menggunakan tensorflow
Y_tf = tf.Variable([[2, 3, 3], [4, 2, 1]])
Y_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[2, 3, 3],
       [4, 2, 1]], dtype=int32)>

In [ ]:
# kalikan matrix X dengan Y
X * Y

array([[ 25,  30,  12],
       [ 40, 188,   4]])

In [ ]:
# kalikan matrix X_pt dengan Y_pt
X_pt * Y_pt

tensor([[ 25,  30,  12],
        [ 40, 188,   4]])

In [ ]:
# kalikan matrix X_tf dengan Y_tf
X_tf * Y_tf

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[50, 45, 18],
       [40, 94,  4]], dtype=int32)>