In [ ]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy

In [ ]:
import numpy as np

In [ ]:
X = np.array([[85,8, 58], [88,58,85]])
X

array([[85,  8, 58],
       [88, 58, 85]])

In [ ]:
# hitung berapa hasil penjumlahan elemen matrix X dengan fungsi sum

In [ ]:
X.sum()

np.int64(382)

In [ ]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
X_tf = tf.Variable([[85,8, 58], [88,58,85]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[85,  8, 58],
       [88, 58, 85]], dtype=int32)>

In [ ]:
# hitung hasil penjumlahan seluruh elemen matrix X

In [ ]:
X.sum()

np.int64(382)

In [ ]:
# hitung hasil penjumlahan seluruh elemen matrix X_pt

In [ ]:
import torch

In [ ]:
X_pt = torch.tensor([[85,8, 58], [88,58,85]])
X_pt

tensor([[85,  8, 58],
        [88, 58, 85]])

In [ ]:
torch.sum(X_pt)

tensor(382)

In [ ]:
# hitung hasil penjumlahan seluruh elemen matrix X_tf

In [ ]:
tf.reduce_sum(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=382>

In [ ]:
# hitung hasil penjumlahan matrix X berdasarkan row nya

In [ ]:
np.sum(X, axis=1)

array([151, 231])

In [ ]:
# hitung hasil penjumlahan matrix X_pt berdasarkan row nya

In [ ]:
torch.sum(X_pt, 1)

tensor([151, 231])

In [ ]:
# hitung hasil penjumlahan matrix X_tf berdasarkan row nya

In [ ]:
tf.reduce_sum(X_tf, 1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([151, 231], dtype=int32)>

In [ ]:
# hitung hasil penjumlahan matrix X berdasarkan kolom nya

In [ ]:
np.sum(X, axis=0)

array([173,  66, 143])

In [ ]:
# hitung hasil penjumlahan matrix X_pt berdasarkan kolom nya

In [ ]:
torch.sum(X_pt, 0)

tensor([173,  66, 143])

In [ ]:
# hitung hasil penjumlahan matrix X_tf berdasarkan kolom nya

In [ ]:
tf.reduce_sum(X_tf, 0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([173,  66, 143], dtype=int32)>

In [ ]:
# hitung nilai minimal dari matrix X, X_pt dan X_tf

In [ ]:
np.min(X)

np.int64(8)

In [ ]:
torch.min(X_pt)

tensor(8)

In [ ]:
tf.reduce_min(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
# hitung nilai maksimal dari matrix X, X_pt dan X_tf

In [ ]:
np.max(X)

np.int64(88)

In [ ]:
torch.max(X_pt)

tensor(88)

In [ ]:
tf.reduce_max(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=88>

In [ ]:
# hitung nilai rata-rata dari matrix X, X_pt dan X_tf

In [ ]:
np.mean(X)

np.float64(63.666666666666664)

In [ ]:
X_pt = X_pt.float()

In [ ]:
torch.mean(X_pt)

tensor(63.6667)

In [ ]:
tf.reduce_mean(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=63>

In [ ]:
# hitung hasil perkalian seluruh elemen matrix X

In [ ]:
np.prod(X)

np.int64(17110649600)

In [ ]:
# hitung hasil perkalian seluruh elemen matrix X_pt

In [ ]:
torch.prod(X_pt)

tensor(1.7111e+10)

In [ ]:
# hitung hasil perkalian seluruh elemen matrix X_tf

In [ ]:
tf.reduce_prod(X_tf)


<tf.Tensor: shape=(), dtype=int32, numpy=-69219584>