In [ ]:
import numpy as np
import torch
import tensorflow as tf

Soal 1

In [ ]:
# buat matrix X dengan ukuran 2x3 menggunakan numpy
X = np.array([[25, 15, 6], [10, 47, 4]])
X

array([[25, 15,  6],
       [10, 47,  4]])

In [ ]:
# buat matrix X_pt dengan ukuran 2x3 menggunakan pytorch
X_pt = torch.tensor([[25, 15, 6], [10, 47, 4]])
X_pt

tensor([[25, 15,  6],
        [10, 47,  4]])

In [ ]:
# buat matrix X_tf dengan ukuran 2x3 menggunakan tensorflow
X_tf = tf.Variable([[25, 15, 6], [10, 47, 4]])
X_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25, 15,  6],
       [10, 47,  4]], dtype=int32)>

Soal 2
lakukan transpose pada matrix X, X_pt dan X_tf

In [ ]:
X.T # Transpose X

array([[25, 10],
       [15, 47],
       [ 6,  4]])

In [ ]:
X_pt.T # Transpose X_pt

tensor([[25, 10],
        [15, 47],
        [ 6,  4]])

In [ ]:
tf.transpose(X_tf) # Transpose X_tf

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[25, 10],
       [15, 47],
       [ 6,  4]], dtype=int32)>