### Frobenius Norm



In [ ]:
import numpy as np

In [ ]:
X = np.array([[1, 2,3], [3, 4,5], [6,7,8]])
X

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
(1**2+2**2+3**2+4**2+5**2+6**2+7**2+8**2)**(1/2)

14.2828568570857

In [ ]:
np.linalg.norm(X) # same function as for vector L2 norm

np.float64(14.594519519326424)

# Menggunakan Pytorch

In [ ]:
import torch

In [ ]:
X_pt = torch.tensor([[1, 2,3], [3, 4,5], [6,7,8]]) # torch.norm() supports floats only
X_pt

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

In [ ]:
torch.norm(X_pt.float())

tensor(14.5945)

# Menggunakan Tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
X_tf = tf.Variable([[1, 2,3], [3, 4,5], [6,7,8]]) # tf.norm() also supports floats only
X_tf

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [ ]:
tf.norm(tf.cast(X_tf, tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=14.59451961517334>