# Matrix Multiplication (with a Vector)

In [ ]:
import numpy as np

In [ ]:
A = np.array([[7, 2,3], [6, 3,4]])
A

array([[7, 2, 3],
       [6, 3, 4]])

In [ ]:
b = np.array ([7,8,9])
b

array([7, 8, 9])

In [ ]:
np.dot(A, b) # even though technically dot products are between vectors only

array([ 92, 102])

# Using Pytorch

In [ ]:
import torch

In [ ]:
A_pt = torch.tensor([[7, 2,3], [6, 3,4]])
A_pt

tensor([[7, 2, 3],
        [6, 3, 4]])

In [ ]:
b_pt = torch.tensor([7,8,9])
b_pt

tensor([7, 8, 9])

In [ ]:
torch.matmul(A_pt, b_pt)

tensor([ 92, 102])

# Using Tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
A_tf = tf.Variable([[7, 2,3], [6, 3,4]])
A_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[7, 2, 3],
       [6, 3, 4]], dtype=int32)>

In [ ]:
b_tf = tf.Variable([7,8,9])
b_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([7, 8, 9], dtype=int32)>

In [ ]:
tf.linalg.matvec(A_tf, b_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 92, 102], dtype=int32)>

# Matrix Multiplication (with Two Matrices)

In [ ]:
A = np.array([[7, 2,3], [6, 3,4]])
A

array([[7, 2, 3],
       [6, 3, 4]])

In [ ]:
B = np.array ([[1,2,3], [4,5,6], [7,8,9]])
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.dot (A, B)

array([[36, 48, 60],
       [46, 59, 72]])

# Note that matrix multiplication is not "commutative" (i.e., $AB \neq BA$) so uncommenting the following line will throw a size mismatch error

In [ ]:
# np.dot(B, A)

In [ ]:
B_pt = torch.from_numpy(B) # much cleaner than TF conversion
B_pt

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# another neat way to create the same tensor with transposition:
B_pt = torch.tensor ([[1,2,3], [4,5,6], [7,8,9]]).T
B_pt

tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [ ]:
torch.matmul(A_pt, B_pt) # no need to change functions, unlike in TF

tensor([[ 20,  56,  92],
        [ 24,  63, 102]])

Using Tensorflow

In [ ]:
import tensorflow as tf

In [ ]:
B_tf = tf.convert_to_tensor(B, dtype=tf.int32)
B_tf

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [ ]:
tf.matmul(A_tf, B_tf)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[36, 48, 60],
       [46, 59, 72]], dtype=int32)>