**Matrix Inversion**

In [ ]:
import numpy as np

In [ ]:
#membuat matrix X ukuran 2x2 menggunakan numpy
X = np.array([[2, 1],
              [5, 3]])
X

array([[2, 1],
       [5, 3]])

In [ ]:
#membuat invers dari matrix X dan beri nama Xinv menggunakan numpy
Xinv = np.linalg.inv(X)
Xinv

array([[ 3., -1.],
       [-5.,  2.]])

In [ ]:
#kalikan X dengan Xinv menggunakan numpy
np.dot(X,Xinv)

array([[ 1.00000000e+00,  2.22044605e-16],
       [-8.88178420e-16,  1.00000000e+00]])

In [ ]:
#Numpy
A = np.array([[4, 2],
              [-5, -3]])
B = np.array([4, -7])
np.linalg.solve(A, B)

array([-1.,  4.])

In [ ]:
#Tensorflow
import tensorflow as tf
A = tf.constant([[4.0, 2.0],
                 [-5.0, -3.0]])
B = tf.constant([[4.0],
                 [-7.0]])
tf.linalg.solve(A, B)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[-0.99999946],
       [ 3.999999  ]], dtype=float32)>

In [ ]:
#Pytorch
import torch
A = torch.tensor([[4.0, 2.0],
                  [-5.0, -3.0]])
B = torch.tensor([[4.0],
                  [-7.0]])
torch.linalg.solve(A, B)

tensor([[-1.],
        [ 4.]])