**Matrix** **Multiplication** **Exercises**

In [ ]:
import numpy as np
import torch
X = np.array([[23, 5], [3, 21], [6, 7]])
X

array([[23,  5],
       [ 3, 21],
       [ 6,  7]])

In [ ]:
X*5

array([[115,  25],
       [ 15, 105],
       [ 30,  35]])

In [ ]:
X_p = torch.tensor([[26,7],[28,4],[15,17]])
X_p

tensor([[26,  7],
        [28,  4],
        [15, 17]])

In [ ]:
X_p*15+5

tensor([[395, 110],
        [425,  65],
        [230, 260]])

In [ ]:
B = np.array([[2, 4], [8, 2], [6, 4]])
B

array([[2, 4],
       [8, 2],
       [6, 4]])

perkalian matrix dengan vektor

In [ ]:
b = np.array([8,2])
b

array([8, 2])

In [ ]:
np.dot(X, b)

array([194,  66,  62])

In [ ]:
b_p = torch.tensor([2,8])
b_p

tensor([2, 8])

In [ ]:
torch.matmul(X_p, b_p)

tensor([108,  88, 166])

perkalian dengan matrix 2x2

In [ ]:
C = np.array([[8,5],[5,4]])
C

array([[8, 5],
       [5, 4]])

In [ ]:
np.dot(B,C)

array([[36, 26],
       [74, 48],
       [68, 46]])

In [ ]:
B_p = torch.tensor([[17,12],[10,5]])
B_p

tensor([[17, 12],
        [10,  5]])

In [ ]:
torch.matmul(X_p,B_p)

tensor([[512, 347],
        [516, 356],
        [425, 265]])